[package]
name = "rtile"
version = "0.0.7"
edition = "2021"
exclude = ["/tests"]
description = "text processing"
license = "MIT"
documentation = "https://docs.rs/rtile/latest/rtile"
repository = "https://github.com/madanmohany/rtile"
readme = "README.md"
keywords = ["template"]
categories = ["template-engine"]

[lib]
name = "rtile"
crate-type = ["dylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
