[package]
name = "rtile"
version = "0.1.3"
edition = "2021"
exclude = ["/tests"]
description = "code generation"
license = "MIT"
documentation = "https://docs.rs/rtile"
repository = "https://github.com/madanmohany/rtile"
readme = "README.md"
keywords = ["code-generation", "template"]
categories = ["template-engine"]

[lib]
name = "rtile"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
