[package]
name = "rtile"
version = "0.1.2"
edition = "2021"
exclude = ["/tests"]
description = "Provides a way to work with rectangular areas of text as atomic units. Can be used for code generation or to generate any pattern of text."
license = "MIT"
repository = "https://github.com/madanmohany/rtile"
readme = "README.md"
keywords = ["code-generation", "template"]
categories = ["template-engine"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
